name: bonsai-orgym
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.4
  - pip=21.1.3
  - pip:
    - numpy==1.19.4
    - pandas==0.24.2
    - vpython==7.6.0
    - microsoft-bonsai-api==0.1.3
    - bonsai-cli==1.0.11
    - python-dotenv==0.13.0
    - gym==0.17.1
    - jupyterlab
    - mip
    - matplotlib
    - scipy